owner: SRESchool
repo: AllWizbrand-monitor-upptime
user-agent: SRESchool
skipReadme: true
skipDescriptionUpdate: true
skipTopicsUpdate: true

assignees:
  - SRESchool

status-website:
  cname: null
  baseUrl: /AllWizbrand-monitor-upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime/master/assets/icon.svg
  name: Wizbrand Uptime Monitor
  introTitle: "Wizbrand Websites Uptime and SSL Status"
  introMessage: This is a status page monitoring the uptime and SSL certificates of Wizbrand-related websites.
  
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
 

workflowSchedule:
  graphs: "*/5 * * * *"
  responseTime: "*/5 * * * *"
  staticSite: "*/5 * * * *"
  summary: "*/5 * * * *"
  updateTemplate: "*/5 * * * *"
  updates: "*/5 * * * *"
  uptime: "*/5 * * * *"
sites:
  - name: AIRegistry
    url: https://airegistry.co
    ssl:
      enabled: true
  - name: GuestPostAI
    url: https://guestpostai.com
    ssl:
      enabled: true
  - name: Wizbrand
    url: https://wizbrand.com
    ssl:
      enabled: true
  - name: GurukulGalaxy
    url: https://gurukulgalaxy.com
    ssl:
      enabled: true
  - name: CMSGalaxy
    url: https://cmsgalaxy.com
    ssl:
      enabled: true
      port: 80
    check: "tcp-ping"
    ipv6: true

   notifications:
  - type: email
    smtpHost: smtp.gmail.com
    smtpPort: 587
    smtpUsername: contact@motoshare.in
    smtpPassword: rbcx sihi gquh ljts 
    smtpFrom: contact@motoshare.in
    smtpTo: contact@motoshare.in
